# -*- coding: utf-8 -*-
"""etl_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQPA62-DfUBiKVSQ7-Fzj6ZLrUD2ZU8b
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("E-Commerce ETL Pipeline") \
    .getOrCreate()

df = spark.read.csv("ecommerce_customer_churn_dataset.csv", header=True, inferSchema=True)

df.show(5)

from pyspark.sql.functions import col

df = df.fillna({
    "Pages_Per_Session": 0,
    "Social_Media_Engagement_Score": 0,
    "Payment_Method_Diversity": 0
})

df = df.dropDuplicates()

from pyspark.sql.functions import upper

df = df.withColumn("Gender", upper(col("Gender")))
df = df.withColumn("Country", upper(col("Country")))

df = df.withColumn("Engagement_Score",
    col("Login_Frequency") +
    col("Session_Duration_Avg") +
    col("Pages_Per_Session") +
    col("Social_Media_Engagement_Score")
)

from pyspark.sql.functions import when

df = df.withColumn("Customer_Value_Segment",
    when(col("Lifetime_Value") > 3000, "High Value")
    .when(col("Lifetime_Value") > 1500, "Medium Value")
    .otherwise("Low Value")
)

df = df.withColumn("Churn_Risk",
    when((col("Days_Since_Last_Purchase") > 60) & (col("Login_Frequency") < 10), "High Risk")
    .when(col("Days_Since_Last_Purchase") > 30, "Medium Risk")
    .otherwise("Low Risk")
)

churn_count = df.groupBy("Churned").count()

from pyspark.sql.functions import sum as _sum

revenue_country = df.groupBy("Country") \
    .agg(_sum("Lifetime_Value").alias("Total_Revenue"))

high_value_customers = df.filter(col("Customer_Value_Segment") == "High Value")

from pyspark.sql.functions import avg

engagement_analysis = df.groupBy("Churned") \
    .agg(avg("Engagement_Score").alias("Avg_Engagement"))

df.write.mode("overwrite").parquet("output/clean_data")

revenue_country.write.mode("overwrite").parquet("output/revenue_country")

churn_count.write.mode("overwrite").parquet("output/churn_analysis")

print("Total records:", df.count())

print("Null values in Engagement:",
      df.filter(col("Engagement_Score").isNull()).count())

print("Distinct countries:",
      df.select("Country").distinct().count())

from pyspark.sql.functions import col

df = df.fillna({
    "Pages_Per_Session": 0,
    "Social_Media_Engagement_Score": 0,
    "Login_Frequency": 0,
    "Session_Duration_Avg": 0
})

df = df.withColumn("Engagement_Score",
    col("Login_Frequency") +
    col("Session_Duration_Avg") +
    col("Pages_Per_Session") +
    col("Social_Media_Engagement_Score")
)

print("Null values in Engagement:",
      df.filter(col("Engagement_Score").isNull()).count())

df.write.mode("overwrite").parquet("output/clean_data")

revenue_country.write.mode("overwrite").parquet("output/revenue_country")

churn_count.write.mode("overwrite").parquet("output/churn_analysis")

df.select("Engagement_Score").show(5)